#!/usr/bin/env node
// Regenerates extensions/omarchy-menu.snippet.jsonc, a "Style > Menu Bar >
// Glyph Mark" submenu, one row per Glyphs.js entry, from the same
// single source of truth used by manifest.json. Run after editing Glyphs.js.
//
// This file is a fragment, not a standalone menu config: it holds only the
// new keys, which the user pastes into their own
// ~/.config/omarchy/extensions/omarchy-menu.jsonc by hand. A plugin cannot
// register menu rows on its own; see README.md.
"use strict"

const fs = require("fs")
const path = require("path")

const root = path.join(__dirname, "..")
const { glyphs } = require(path.join(root, "Glyphs.js"))

const PLUGIN_ID = "io.github.smoothpixels.glyph-menu"
const PLUGIN_DIR = `$HOME/.config/omarchy/plugins/${PLUGIN_ID}`

function jsonString(value) {
  return JSON.stringify(value)
}

// No "checked" state on the rows: Omarchy has no command that reads a bar
// widget's settings, and reading shell.json from a plugin script is exactly
// the kind of config access this plugin avoids. The built-in Style > Menu
// Bar > Position rows don't show one either.

const lines = []
lines.push('  "style.bar.glyph": {"icon":"\\uf03e","label":"Glyph Mark","description":"Pick the icon shown by the Glyph Menu plugin"},')

for (const g of glyphs()) {
  const icon = String.fromCodePoint(parseInt(g.code, 16))
  // Glyphs outside a Nerd Font (currently only "omarchy") need their own
  // iconFont so the row renders through the font that actually has the
  // codepoint, instead of the menu's own font family.
  const iconFont = g.font ? `,"iconFont":${jsonString(g.font)}` : ""
  const line = `  "style.bar.glyph.${g.id}": {"icon":${jsonString(icon)}${iconFont},"label":${jsonString(g.label)},"action":${jsonString(`omarchy bar set ${PLUGIN_ID} mark ${g.id}`)}},`
  lines.push(line)
}

lines.push(`  "style.bar.glyph.custom": {"icon":"\\uf040","label":"Custom text\\u2026","action":${jsonString(`omarchy-launch-floating-terminal-with-presentation '${PLUGIN_DIR}/tools/set-custom.sh'`)}},`)

const header = `// Generated by tools/sync-menu.js from Glyphs.js. Do not edit by hand;
// edit Glyphs.js and re-run the generator instead.
//
// This is a fragment: the keys below, not a full omarchy-menu.jsonc file.
// Paste them inside the outer { } of your own
// ~/.config/omarchy/extensions/omarchy-menu.jsonc (see README.md).
`

const output = header + lines.join("\n") + "\n"
const outPath = path.join(root, "extensions", "omarchy-menu.snippet.jsonc")
fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, output)
console.log("Wrote " + (lines.length - 1) + " menu rows to extensions/omarchy-menu.snippet.jsonc")
