#!/usr/bin/env node
// Regenerates extensions/omarchy-menu.snippet.jsonc — a "Style > Menu Bar >
// Glyph Mark" submenu, one checkable row per Glyphs.js entry — from the same
// single source of truth used by manifest.json. Run after editing Glyphs.js.
//
// This file is a fragment, not a standalone menu config: it holds only the
// new keys, meant to be spliced into the user's own
// ~/.config/omarchy/extensions/omarchy-menu.jsonc (see
// tools/install-menu-entries.sh). A plugin cannot register menu rows on its
// own — see README.md.
"use strict"

const fs = require("fs")
const path = require("path")

const root = path.join(__dirname, "..")
const { glyphs } = require(path.join(root, "Glyphs.js"))

const PLUGIN_ID = "io.github.SmoothPixels.glyph-menu"
const PLUGIN_DIR = `$HOME/.config/omarchy/plugins/${PLUGIN_ID}`
const CURRENT_MARK = `${PLUGIN_DIR}/tools/current-mark.sh`

function jsonString(value) {
  return JSON.stringify(value)
}

function checkedFor(id) {
  return jsonString(`[[ "$(${CURRENT_MARK})" == "${id}" ]]`)
}

const lines = []
lines.push('  "style.bar.glyph": {"icon":"\\uf03e","label":"Glyph Mark","description":"Pick the icon shown by the Glyph Menu plugin"},')

for (const g of glyphs()) {
  const icon = String.fromCodePoint(parseInt(g.code, 16))
  const line = `  "style.bar.glyph.${g.id}": {"icon":${jsonString(icon)},"label":${jsonString(g.label)},"checked":${checkedFor(g.id)},"action":${jsonString(`omarchy bar set ${PLUGIN_ID} mark ${g.id}`)}},`
  lines.push(line)
}

lines.push(`  "style.bar.glyph.custom": {"icon":"\\uf040","label":"Custom text\\u2026","checked":${checkedFor("custom")},"action":${jsonString(`omarchy-launch-floating-terminal-with-presentation '${PLUGIN_DIR}/tools/set-custom.sh'`)}},`)

const header = `// Generated by tools/sync-menu.js from Glyphs.js. Do not edit by hand —
// edit Glyphs.js and re-run the generator instead.
//
// This is a fragment: the keys below, not a full omarchy-menu.jsonc file.
// Install with tools/install-menu-entries.sh, which splices them into
// ~/.config/omarchy/extensions/omarchy-menu.jsonc.
`

const output = header + lines.join("\n") + "\n"
const outPath = path.join(root, "extensions", "omarchy-menu.snippet.jsonc")
fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, output)
console.log("Wrote " + (lines.length - 1) + " menu rows to extensions/omarchy-menu.snippet.jsonc")
